-- E-commerce OLTP schema (Stage 1)

CREATE TABLE users (
    user_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(150) NOT NULL UNIQUE,
    country     VARCHAR(60)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE sellers (
    seller_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_name  VARCHAR(120) NOT NULL,
    rating       NUMERIC(2,1) CHECK (rating BETWEEN 1 AND 5),
    created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE categories (
    category_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE products (
    product_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    INT NOT NULL REFERENCES sellers(seller_id),
    category_id  INT NOT NULL REFERENCES categories(category_id),
    name         VARCHAR(150) NOT NULL,
    price        NUMERIC(10,2) NOT NULL CHECK (price > 0),
    stock        INT NOT NULL DEFAULT 0 CHECK (stock >= 0)
);

CREATE TABLE orders (
    order_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT NOT NULL REFERENCES users(user_id),
    order_date    TIMESTAMP NOT NULL,
    status        VARCHAR(20) NOT NULL
                  CHECK (status IN ('pending','paid','shipped','delivered','cancelled','returned')),
    total_amount  NUMERIC(12,2) NOT NULL
);

CREATE TABLE order_items (
    order_item_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       INT NOT NULL REFERENCES orders(order_id),
    product_id     INT NOT NULL REFERENCES products(product_id),
    quantity       INT NOT NULL CHECK (quantity > 0),
    unit_price     NUMERIC(10,2) NOT NULL
);

CREATE TABLE payments (
    payment_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INT NOT NULL REFERENCES orders(order_id),
    method      VARCHAR(30) NOT NULL,
    amount      NUMERIC(12,2) NOT NULL,
    status      VARCHAR(20) NOT NULL CHECK (status IN ('success','failed','refunded')),
    paid_at     TIMESTAMP
);

CREATE TABLE reviews (
    review_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT NOT NULL REFERENCES users(user_id),
    product_id   INT NOT NULL REFERENCES products(product_id),
    rating       INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_date  TIMESTAMP NOT NULL
);

CREATE TABLE events (
    event_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INT REFERENCES users(user_id),
    product_id  INT REFERENCES products(product_id),
    event_type  VARCHAR(20) NOT NULL
                CHECK (event_type IN ('view','add_to_cart','remove_from_cart','purchase')),
    event_time  TIMESTAMP NOT NULL
);

CREATE INDEX idx_orders_user      ON orders(user_id);
CREATE INDEX idx_orders_date      ON orders(order_date);
CREATE INDEX idx_items_order      ON order_items(order_id);
CREATE INDEX idx_items_product    ON order_items(product_id);
CREATE INDEX idx_payments_order   ON payments(order_id);
CREATE INDEX idx_reviews_product  ON reviews(product_id);
CREATE INDEX idx_events_time      ON events(event_time);
CREATE INDEX idx_events_user      ON events(user_id);
